openapi: 3.0.1
info:
  title: Notion Assistant API
  version: '1.0'
servers:
  - url: https://notion-sdk-typescript-starter.onrender.com

paths:
  /api/notion/create-database:
    post:
      operationId: createDatabase
      summary: Create a new Notion database inside a page
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parentPageId:
                  type: string
                databaseTitle:
                  type: string
              required:
                - parentPageId
                - databaseTitle
      responses:
        '200':
          description: Database created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  databaseId:
                    type: string
        '400':
          description: Invalid input
        '500':
          description: Server error
